name       : haskell-time-locale-compat
version    : 0.1.1.4
release    : 4
source     :
    - https://hackage.haskell.org/package/time-locale-compat-0.1.1.4/time-locale-compat-0.1.1.4.tar.gz : f2d165557e2bbd014a4d6615b3e6c177adb034179a307a775e06836f91ebbe62
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package contains wrapped name module for TimeLocale
description: |
    This package contains wrapped name module for TimeLocale
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
