name       : haskell-time-locale-compat
version    : 0.1.1.3
release    : 2
source     :
    - https://hackage.haskell.org/package/time-locale-compat-0.1.1.3/time-locale-compat-0.1.1.3.tar.gz : 9144bf68b47791a2ac73f45aeadbc5910be2da9ad174909e1a10a70b4576aced
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package contains wrapped name module for TimeLocale
description: |
    This package contains wrapped name module for TimeLocale
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
