name       : haskell-time-locale-compat
version    : 0.1.1.3
release    : 1
source     :
    - https://hackage.haskell.org/package/time-locale-compat-0.1.1.3/time-locale-compat-0.1.1.3.tar.gz : 9144bf68b47791a2ac73f45aeadbc5910be2da9ad174909e1a10a70b4576aced
license    : BSD-3-Clause
component  : programming
summary    : This package contains wrapped name module for TimeLocale
description: |
    This package contains wrapped name module for TimeLocale
builddeps  :
    - ghc
setup      : |
    sudo ghc-pkg recache
    ghc -threaded Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --datadir=/usr/share \
                      --sysconfdir=/etc \
                      --libexecdir=/usr/lib64/cabal \
                      --libsubdir="\$compiler/\$pkgid"
build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 time-locale-compat-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/time-locale-compat-$version.conf

