name       : haskell-time-locale-compat
version    : 0.1.1.5
release    : 6
source     :
    - https://hackage.haskell.org/package/time-locale-compat-0.1.1.5/time-locale-compat-0.1.1.5.tar.gz : 07ff1566de7d851423a843b2de385442319348c621d4f779b3d365ce91ac502c
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package contains wrapped name module for TimeLocale
description: |
    This package contains wrapped name module for TimeLocale
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
